services:
  zenoh-router:
    image: eclipse/zenoh:latest
    container_name: zenoh-router
    ports:
      - "7447:7447"
      - "7447:7447/udp"
      - "8000:8000"
    restart: unless-stopped

  #zenoh-mqtt-bridge:
  #  image: eclipse/zenoh-bridge-mqtt:latest
  #  container_name: zenoh-mqtt-bridge
  #  environment:
  #    - RUST_LOG=info
  #  command: [
  #    "--connect", "tcp/zenoh-router:7447", 
  #    "--broker", "tcp://plugfest.thingweb.io:8887",
  #    "--scope", "wotpy"
  #  ]
  #  depends_on:
  #    - zenoh-router
  #  restart: unless-stopped